# Generated by Django 4.0.3 on 2022-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('special_price', models.IntegerField(null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('promotion_end_at', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
